<template>
  <div class="mx-auto max-w-7xl space-y-6">
    <header class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><Link :href="resolveRoute('workflows.index')" class="text-sm font-semibold text-blue-600">← Workflows</Link><div class="mt-2 flex flex-wrap items-center gap-3"><h1 class="text-3xl font-bold text-slate-900 dark:text-white">{{ workflow.name }}</h1><span :class="workflow.is_active ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-200 text-slate-600'" class="rounded-full px-3 py-1 text-xs font-bold">{{ workflow.is_active ? 'Aktif' : 'Nonaktif' }}</span></div><p class="mt-1 font-mono text-sm text-slate-400">{{ workflow.code }} · {{ workflow.entity_type }}</p></div><Link v-if="can.update" :href="resolveRoute('workflows.edit', { workflow: workflow.uuid })" class="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">Edit Workflow</Link></header>
    <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="card"><p class="label">Total {{ entityLabel }}</p><p class="value">{{ workflow.total_items_count }}</p></div><div class="card"><p class="label">Sedang berjalan</p><p class="value !text-amber-600">{{ workflow.running_items_count }}</p></div><div class="card"><p class="label">Selesai</p><p class="value !text-emerald-600">{{ workflow.completed_items_count }}</p></div><div class="card"><p class="label">Tahapan</p><p class="value">{{ workflow.stages.length }}</p></div></section>
    <section class="card"><div class="flex flex-wrap items-start justify-between gap-3"><div><h2 class="text-lg font-bold dark:text-white">Visual tahapan workflow</h2><p class="mt-1 text-sm text-slate-500">{{ workflow.description || 'Tidak ada deskripsi.' }}</p></div><span class="rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-700 dark:bg-blue-500/10 dark:text-blue-300">Sinkron dengan status {{ entityLabel }}</span></div><div class="mt-6 overflow-x-auto pb-2"><div class="flex min-w-max items-stretch"><template v-for="(stage, index) in workflow.stages" :key="stage.id"><article class="w-64 rounded-2xl border border-blue-100 bg-blue-50/60 p-4 dark:border-blue-500/20 dark:bg-blue-500/5"><div class="flex items-center gap-3"><span class="flex h-9 w-9 items-center justify-center rounded-full bg-blue-600 font-bold text-white">{{ index + 1 }}</span><div class="min-w-0 flex-1"><h3 class="truncate font-bold text-slate-800 dark:text-white">{{ stage.name }}</h3><p class="text-xs capitalize text-blue-600">{{ stage.status_key.replaceAll('_', ' ') }}</p></div><span class="rounded-full bg-white px-2 py-1 text-xs font-bold text-blue-700 shadow-sm dark:bg-slate-800 dark:text-blue-300">{{ stage.instances_count }}</span></div><div class="mt-4 space-y-2 text-xs text-slate-500"><p>Role: <b>{{ stage.responsible_role || '—' }}</b></p><p>PIC: <b>{{ stage.responsible_user_name || '—' }}</b></p><p>Aksi: <b>{{ stage.action_label || '—' }}</b></p></div></article><div v-if="index < workflow.stages.length - 1" class="flex w-14 items-center justify-center text-blue-400"><span class="material-icons">arrow_forward</span></div></template></div></div></section>
    <div class="grid gap-6 lg:grid-cols-2"><section class="card"><h2 class="text-lg font-bold dark:text-white">Kondisi pemicu</h2><div v-if="!workflow.trigger_conditions.length" class="mt-4 text-sm text-slate-500">Berlaku untuk semua {{ workflow.entity_type }}.</div><ul v-else class="mt-4 space-y-2"><li v-for="(item, index) in workflow.trigger_conditions" :key="index" class="rounded-xl bg-slate-50 px-4 py-3 text-sm dark:bg-slate-800"><b class="capitalize">{{ item.field }}</b> {{ operator(item.operator) }} “{{ item.value }}”</li></ul></section><section class="card"><h2 class="text-lg font-bold dark:text-white">Riwayat perubahan</h2><div v-if="!workflow.histories.length" class="mt-4 text-sm text-slate-500">Belum ada riwayat.</div><ol v-else class="mt-4 space-y-4"><li v-for="history in workflow.histories" :key="history.id" class="border-l-2 border-blue-200 pl-4"><p class="text-sm font-semibold capitalize text-slate-700 dark:text-slate-200">{{ history.event }}</p><p class="text-xs text-slate-500">{{ history.actor_name }} · {{ formatDate(history.created_at) }}</p></li></ol></section></div>
    <section class="card overflow-hidden !p-0">
      <div class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 px-5 py-4 dark:border-slate-700"><div><h2 class="text-lg font-bold dark:text-white">Daftar {{ entityLabel }} nyata</h2><p class="mt-1 text-sm text-slate-500">Data langsung dari database yang menggunakan workflow ini.</p></div><span class="text-sm font-semibold text-slate-500">{{ instances.total }} item</span></div>
      <div v-if="!instances.data.length" class="flex min-h-52 flex-col items-center justify-center px-6 py-10 text-center"><span class="material-icons text-5xl text-slate-300">inventory_2</span><p class="mt-3 font-semibold text-slate-700 dark:text-slate-200">Belum ada {{ entityLabel }} pada workflow ini</p></div>
      <div v-else class="overflow-x-auto"><table class="min-w-[920px] w-full divide-y divide-slate-200 dark:divide-slate-700"><thead class="bg-slate-50 dark:bg-slate-800/70"><tr class="text-left text-xs font-bold uppercase tracking-wider text-slate-500"><th class="px-5 py-3">Nomor / Judul</th><th class="px-5 py-3">Requester</th><th class="px-5 py-3">PIC</th><th class="px-5 py-3">Status saat ini</th><th class="px-5 py-3">Tanggal</th><th class="px-5 py-3 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800"><tr v-for="item in instances.data" :key="item.id" class="hover:bg-slate-50 dark:hover:bg-slate-800/50"><td class="px-5 py-4"><p class="font-mono text-xs font-semibold text-blue-600">{{ item.number }}</p><p class="mt-1 max-w-sm truncate font-semibold text-slate-800 dark:text-white">{{ item.title }}</p></td><td class="px-5 py-4 text-sm text-slate-600 dark:text-slate-300">{{ item.requester }}</td><td class="px-5 py-4 text-sm text-slate-600 dark:text-slate-300">{{ item.pic }}</td><td class="px-5 py-4"><span :class="statusClass(item.status)" class="rounded-full px-2.5 py-1 text-xs font-semibold">{{ item.stage_name }} · {{ item.status_label }}</span></td><td class="px-5 py-4 text-sm text-slate-500">{{ formatDate(item.date, false) }}</td><td class="px-5 py-4 text-right"><Link :href="item.detail_url" class="inline-flex items-center gap-1 rounded-lg border border-blue-200 px-3 py-2 text-xs font-semibold text-blue-700 hover:bg-blue-50 dark:border-blue-500/30 dark:text-blue-300"><span class="material-icons text-base">open_in_new</span> Detail</Link></td></tr></tbody></table></div>
      <div v-if="instances.links?.length > 3" class="flex flex-wrap items-center justify-between gap-3 border-t border-slate-200 px-5 py-4 dark:border-slate-700"><p class="text-xs text-slate-500">Menampilkan {{ instances.from }}–{{ instances.to }} dari {{ instances.total }}</p><nav class="flex gap-1"><template v-for="link in instances.links" :key="link.label"><Link v-if="link.url" :href="link.url" preserve-scroll v-html="link.label" class="rounded-lg border px-3 py-1.5 text-xs" :class="link.active ? 'border-blue-600 bg-blue-600 text-white' : 'border-slate-200 text-slate-600 dark:border-slate-700 dark:text-slate-300'" /><span v-else v-html="link.label" class="cursor-not-allowed rounded-lg border border-slate-100 px-3 py-1.5 text-xs text-slate-300 dark:border-slate-800 dark:text-slate-600"></span></template></nav></div>
    </section>
  </div>
</template>
<script setup>
import { Link } from '@inertiajs/vue3'
import AppLayout from '../../Layouts/AppLayout.vue'
import resolveRoute from '../../utils/resolveRoute'
defineOptions({ layout: AppLayout })
const props = defineProps({ workflow: { type: Object, required: true }, instances: { type: Object, required: true }, can: { type: Object, default: () => ({}) } })
const entityLabel = props.workflow.entity_type === 'ticket' ? 'Ticket' : 'Task'
const operator = value => ({ equals: 'sama dengan', not_equals: 'tidak sama dengan', contains: 'mengandung' }[value] || value)
const formatDate = (value, includeTime = true) => value ? new Intl.DateTimeFormat('id-ID', includeTime ? { dateStyle: 'medium', timeStyle: 'short' } : { dateStyle: 'medium' }).format(new Date(value)) : '—'
const statusClass = value => value === 'done' ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-300' : value === 'cancelled' ? 'bg-rose-50 text-rose-700 dark:bg-rose-500/10 dark:text-rose-300' : 'bg-blue-50 text-blue-700 dark:bg-blue-500/10 dark:text-blue-300'
</script>
<style scoped>
.card { border: 1px solid #e2e8f0; border-radius: 1rem; background: white; padding: 1.25rem; box-shadow: 0 1px 2px rgb(15 23 42 / .04); }
.dark .card { border-color: #334155; background: #0f172a; }
.label { font-size: .72rem; font-weight: 700; text-transform: uppercase; letter-spacing: .08em; color: #94a3b8; }
.value { margin-top: .35rem; font-size: 1.35rem; font-weight: 700; color: #0f172a; }
.dark .value { color: white; }
</style>
