<template>
  <div class="mx-auto max-w-7xl space-y-6">
    <Head title="Workflows" />
    <Transition name="fade"><div v-if="notice" :class="notice.type === 'error' ? 'border-rose-200 bg-rose-50 text-rose-700' : 'border-emerald-200 bg-emerald-50 text-emerald-700'" class="fixed right-5 top-20 z-[70] max-w-sm rounded-xl border px-4 py-3 text-sm font-semibold shadow-lg">{{ notice.message }}</div></Transition>
    <header class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
      <div><Link :href="resolveRoute('workflows.index')" class="text-sm font-semibold text-cyan-600">← Workflow Command Center</Link><div class="mt-2 flex flex-wrap items-center gap-3"><h1 class="text-3xl font-bold text-slate-900 dark:text-white">{{ workflow.name }}</h1><span :class="workflow.is_active ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-200 text-slate-600'" class="rounded-full px-3 py-1 text-xs font-bold">{{ workflow.is_active ? 'Aktif' : 'Nonaktif' }}</span><span class="rounded-full bg-cyan-50 px-3 py-1 text-xs font-bold text-cyan-700">v{{ workflow.version }}</span></div><p class="mt-1 font-mono text-sm text-slate-400">{{ workflow.code }} · {{ workflow.entity_type }}</p></div>
      <Dropdown v-if="can.update || can.toggle || can.delete" width-class="w-52"><template #trigger><span class="material-icons">more_horiz</span><span class="ml-2 text-sm font-semibold">Aksi Workflow</span></template><Link v-if="can.update" :href="resolveRoute('workflows.edit',{workflow:workflow.slug})" class="menu"><span class="material-icons">edit</span>Edit Workflow</Link><button v-if="can.toggle" type="button" class="menu w-full" @click="confirmWorkflow('toggle')"><span class="material-icons">power_settings_new</span>{{ workflow.is_active ? 'Nonaktifkan' : 'Aktifkan' }}</button><button v-if="can.delete" type="button" class="menu danger w-full" @click="confirmWorkflow('delete')"><span class="material-icons">delete</span>Hapus Workflow</button></Dropdown>
    </header>

    <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="metric"><p>Total {{ entityLabel }}</p><strong>{{ workflow.total_items_count }}</strong></div><div class="metric"><p>Sedang berjalan</p><strong class="text-amber-600">{{ workflow.running_items_count }}</strong></div><div class="metric"><p>Selesai</p><strong class="text-emerald-600">{{ workflow.completed_items_count }}</strong></div><div class="metric"><p>Tahapan</p><strong>{{ workflow.stages.length }}</strong></div></section>

    <section class="grid gap-4 lg:grid-cols-[1.5fr_1fr]">
      <div class="card"><div class="flex items-start gap-3"><span class="material-icons rounded-xl bg-cyan-50 p-2 text-cyan-600">schema</span><div><h2 class="font-bold dark:text-white">Ringkasan Definisi</h2><p class="mt-1 text-sm leading-relaxed text-slate-500">{{ workflow.description || 'Tidak ada deskripsi workflow.' }}</p></div></div><dl class="mt-5 grid gap-4 text-sm sm:grid-cols-2"><div><dt class="label">Dibuat oleh</dt><dd>{{ workflow.creator_name }}</dd></div><div><dt class="label">Terakhir diubah</dt><dd>{{ workflow.updater_name }}</dd></div><div><dt class="label">Dibuat</dt><dd>{{ formatDate(workflow.created_at) }}</dd></div><div><dt class="label">Diperbarui</dt><dd>{{ formatDate(workflow.updated_at) }}</dd></div></dl></div>
      <div class="card"><h2 class="font-bold dark:text-white">Kondisi Pemicu</h2><p v-if="!workflow.trigger_conditions.length" class="mt-4 text-sm text-slate-500">Berlaku untuk semua {{ workflow.entity_type }}.</p><ul v-else class="mt-3 space-y-2"><li v-for="(item,index) in workflow.trigger_conditions" :key="index" class="rounded-xl bg-slate-50 px-3 py-2 text-sm dark:bg-slate-800"><b class="capitalize">{{ item.field }}</b> {{ operator(item.operator) }} “{{ item.value }}”</li></ul></div>
    </section>

    <section class="card !p-0 overflow-hidden">
      <div class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 px-5 py-4 dark:border-slate-700"><div><h2 class="text-lg font-bold dark:text-white">Tahapan Workflow</h2><p class="mt-1 text-sm text-slate-500">Urutan, penanggung jawab, kewajiban, progres, dan audit waktu.</p></div><button v-if="can.structure" type="button" class="primary" @click="openStage()"><span class="material-icons text-lg">add</span>Tambah Tahap</button></div>
      <div class="overflow-x-auto"><table class="min-w-[1080px] w-full divide-y divide-slate-200 dark:divide-slate-700"><thead class="bg-slate-50 dark:bg-slate-800/70"><tr class="table-head"><th>Urutan</th><th>Tahap / Status</th><th>Penanggung Jawab</th><th>Sifat</th><th>Progres</th><th>Timestamp</th><th class="text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800"><tr v-for="(stage,index) in workflow.stages" :key="stage.id" class="hover:bg-cyan-50/40 dark:hover:bg-slate-800/50"><td class="px-5 py-4"><span class="order">{{ stage.position }}</span></td><td class="px-5 py-4"><p class="font-semibold text-slate-800 dark:text-white">{{ stage.name }}</p><p class="mt-1 text-xs text-cyan-600">{{ labelStatus(stage.status_key) }}</p><p v-if="stage.instructions" class="mt-1 max-w-xs text-xs text-slate-400">{{ stage.instructions }}</p></td><td class="px-5 py-4 text-sm"><p>{{ stage.responsible_user_name || 'User dinamis' }}</p><p class="text-xs text-slate-400">{{ stage.responsible_role || 'Tanpa role khusus' }}</p></td><td class="px-5 py-4"><span :class="stage.is_required ? 'bg-rose-50 text-rose-700' : 'bg-slate-100 text-slate-600'" class="rounded-full px-2.5 py-1 text-xs font-semibold">{{ stage.is_required ? 'Wajib' : 'Opsional' }}</span></td><td class="px-5 py-4"><p class="font-bold text-slate-800 dark:text-white">{{ stage.instances_count }} item</p><p class="text-xs text-slate-400">{{ progress(stage.instances_count) }} dari workflow</p></td><td class="px-5 py-4 text-xs text-slate-500"><p>Dibuat {{ formatDate(stage.created_at) }}</p><p class="mt-1">Diubah {{ formatDate(stage.updated_at) }}</p></td><td class="px-5 py-4 text-right"><Dropdown v-if="can.structure" width-class="w-48"><template #trigger><span class="material-icons">more_horiz</span></template><button type="button" class="menu w-full" @click="openStage(stage)"><span class="material-icons">edit</span>Edit tahap</button><button v-if="index>0" type="button" class="menu w-full" @click="moveStage(index,-1)"><span class="material-icons">arrow_upward</span>Naikkan</button><button v-if="index<workflow.stages.length-1" type="button" class="menu w-full" @click="moveStage(index,1)"><span class="material-icons">arrow_downward</span>Turunkan</button><button v-if="workflow.stages.length>2 && stage.instances_count===0" type="button" class="menu danger w-full" @click="confirmStageDelete(stage)"><span class="material-icons">delete</span>Hapus tahap</button></Dropdown><span v-else class="text-xs text-slate-400">Terproteksi</span></td></tr></tbody></table></div>
    </section>

    <section class="card !p-0 overflow-hidden"><div class="border-b border-slate-200 px-5 py-4 dark:border-slate-700"><h2 class="text-lg font-bold dark:text-white">{{ entityLabel }} Terkait</h2><p class="mt-1 text-sm text-slate-500">Informasi runtime langsung dari database dan dibatasi sesuai akses akun.</p></div><div v-if="!instances.data.length" class="flex min-h-48 items-center justify-center text-sm text-slate-500">Belum ada {{ entityLabel }} terkait.</div><div v-else class="overflow-x-auto"><table class="min-w-[1250px] w-full divide-y divide-slate-200 dark:divide-slate-700"><thead class="bg-slate-50 dark:bg-slate-800/70"><tr class="table-head"><th>Nomor / Judul</th><th>Requester / Creator</th><th>PIC</th><th>Priority / Target</th><th>Status / Tahap</th><th>Waktu</th><th class="text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800"><tr v-for="item in instances.data" :key="item.id"><td class="px-5 py-4"><Link :href="item.detail_url" class="font-mono text-xs font-bold text-cyan-600">{{ item.number }}</Link><p class="mt-1 max-w-xs truncate font-semibold dark:text-white">{{ item.title }}</p></td><td class="px-5 py-4 text-sm"><p>{{ item.requester }}</p><p class="text-xs text-slate-400">Creator: {{ item.creator }}</p></td><td class="px-5 py-4 text-sm">{{ item.pic }}</td><td class="px-5 py-4 text-sm"><p class="capitalize">{{ item.priority }}</p><p class="text-xs text-slate-400">{{ formatDate(item.target_date,false) }}</p></td><td class="px-5 py-4"><span :class="statusClass(item.status)" class="rounded-full px-2.5 py-1 text-xs font-semibold">{{ item.status_label }}</span><p class="mt-1 text-xs text-slate-500">{{ item.stage_name }}</p></td><td class="px-5 py-4 text-xs text-slate-500"><p>Dibuat {{ formatDate(item.created_at) }}</p><p class="mt-1">Diubah {{ formatDate(item.updated_at) }}</p></td><td class="px-5 py-4 text-right"><Dropdown width-class="w-48"><template #trigger><span class="material-icons">more_horiz</span></template><Link :href="item.detail_url" class="menu"><span class="material-icons">visibility</span>Lihat detail</Link><Link v-if="item.can_edit" :href="item.edit_url" class="menu"><span class="material-icons">edit</span>Edit item</Link><button v-if="item.can_update_status" class="menu w-full" @click="openRuntime(item)"><span class="material-icons">published_with_changes</span>Update status</button></Dropdown></td></tr></tbody></table></div><div v-if="instances.links?.length>3" class="flex justify-end gap-1 border-t border-slate-200 p-4 dark:border-slate-700"><template v-for="link in instances.links" :key="link.label"><Link v-if="link.url" :href="link.url" preserve-scroll v-html="link.label" class="rounded-lg border px-3 py-1.5 text-xs" :class="link.active?'border-cyan-600 bg-cyan-600 text-white':'border-slate-200 text-slate-500'" /></template></div></section>

    <section class="card"><h2 class="text-lg font-bold dark:text-white">Workflow History & Audit</h2><p class="mt-1 text-sm text-slate-500">Perubahan definisi dan perpindahan runtime disimpan kronologis.</p><div v-if="!workflow.histories.length" class="mt-5 text-sm text-slate-500">Belum ada riwayat.</div><ol v-else class="mt-5 grid gap-3 md:grid-cols-2"><li v-for="history in workflow.histories" :key="history.id" class="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><div class="flex items-start justify-between gap-2"><p class="text-sm font-semibold capitalize dark:text-white">{{ history.event.replaceAll('_',' ') }}</p><span class="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold uppercase text-slate-500">{{ history.scope }}</span></div><p class="mt-1 text-xs text-slate-500">{{ history.actor_name }} · {{ formatDate(history.created_at) }}</p><p v-if="history.scope==='runtime'" class="mt-2 text-xs text-cyan-700">{{ history.changes.from || 'Awal' }} → {{ history.changes.to }}</p></li></ol></section>

    <Teleport to="body">
    <div v-if="stageModal" class="backdrop" @click.self="closeStage"><form class="modal max-w-2xl" @submit.prevent="saveStage"><div class="modal-head"><div><p class="eyebrow">Struktur Workflow</p><h3>{{ editingStage ? 'Edit Tahap' : 'Tambah Tahap' }}</h3></div><button type="button" class="close" @click="closeStage">×</button></div><div class="mt-5 grid gap-4 sm:grid-cols-2"><label class="field">Urutan<input v-model.number="stageForm.position" type="number" min="1" :max="editingStage?workflow.stages.length:workflow.stages.length+1" required class="input" /></label><label class="field">Nama tahap<input v-model="stageForm.name" required maxlength="100" class="input" /></label><label class="field">Status<WorkflowSelect v-model="stageForm.status_key" :options="statusOptions" aria-label="Status tahap" /></label><label class="field">Role<WorkflowSelect v-model="stageForm.responsible_role" :options="roleOptions" placeholder="Tanpa role khusus" aria-label="Role penanggung jawab" /></label><label class="field">PIC spesifik<WorkflowSelect v-model="stageForm.responsible_user_id" :options="userOptions" placeholder="User dinamis" aria-label="PIC spesifik" /></label><label class="field">Label aksi<input v-model="stageForm.action_label" maxlength="100" class="input" /></label><label class="field sm:col-span-2">Instruksi<textarea v-model="stageForm.instructions" rows="3" maxlength="1000" class="input"></textarea></label><label class="flex items-center gap-3 text-sm font-semibold"><input v-model="stageForm.is_required" type="checkbox" class="h-5 w-5 rounded text-cyan-600" />Tahap wajib diselesaikan</label></div><div v-if="Object.keys(stageForm.errors).length" class="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{{ Object.values(stageForm.errors)[0] }}</div><div class="actions"><button type="button" class="secondary" @click="closeStage">Batal</button><button :disabled="stageForm.processing" class="primary">{{ stageForm.processing?'Menyimpan...':'Simpan Tahap' }}</button></div></form></div>
    <div v-if="runtimeItem" class="backdrop" @click.self="runtimeItem=null"><form class="modal" @submit.prevent="saveRuntime"><div class="modal-head"><h3>Update Status</h3><button type="button" class="close" @click="runtimeItem=null">×</button></div><p class="mt-2 text-sm text-slate-500">{{ runtimeItem.number }} · {{ runtimeItem.title }}</p><label class="field mt-5">Status tujuan<WorkflowSelect v-model="runtimeForm.status" :options="runtimeItem.status_options" placeholder="Pilih transisi" aria-label="Status tujuan" /></label><p v-if="runtimeForm.errors.status" class="mt-2 text-sm text-rose-600">{{ runtimeForm.errors.status }}</p><div class="actions"><button type="button" class="secondary" @click="runtimeItem=null">Batal</button><button :disabled="runtimeForm.processing" class="primary">Simpan</button></div></form></div>
    <div v-if="confirmation" class="backdrop" @click.self="confirmation=null"><div class="modal"><span class="material-icons rounded-xl bg-rose-50 p-3 text-rose-600">warning</span><h3 class="mt-4 text-xl font-bold dark:text-white">{{ confirmation.title }}</h3><p class="mt-2 text-sm text-slate-500">{{ confirmation.message }}</p><div class="actions"><button class="secondary" @click="confirmation=null">Batal</button><button :disabled="busy" class="rounded-xl bg-rose-600 px-4 py-2.5 text-sm font-semibold text-white" @click="runConfirmation">{{ busy?'Memproses...':'Ya, lanjutkan' }}</button></div></div></div>
    </Teleport>
  </div>
</template>

<script setup>
import { Head, Link, router, useForm, usePage } from '@inertiajs/vue3'
import { computed, onBeforeUnmount, ref, watch } from 'vue'
import axios from 'axios'
import Dropdown from '../../Components/Dropdown.vue'; import AppLayout from '../../Layouts/AppLayout.vue'
import WorkflowSelect from '../../Components/WorkflowSelect.vue'; import resolveRoute from '../../utils/resolveRoute'
defineOptions({layout:AppLayout})
const props=defineProps({workflow:{type:Object,required:true},instances:{type:Object,required:true},can:{type:Object,default:()=>({})},roles:{type:Array,default:()=>[]},users:{type:Array,default:()=>[]},statusOptions:{type:Array,default:()=>[]}})
const roleOptions=computed(()=>[{value:'',label:'Tanpa role khusus'},...props.roles.map(role=>({value:role,label:role}))]), userOptions=computed(()=>[{value:null,label:'User dinamis'},...props.users.map(user=>({value:user.id,label:user.name}))])
const page=usePage(), entityLabel=props.workflow.entity_type==='ticket'?'Ticket':'Task', notice=ref(null), stageModal=ref(false), editingStage=ref(null), runtimeItem=ref(null), confirmation=ref(null), busy=ref(false)
const modalOpen=computed(()=>Boolean(stageModal.value||runtimeItem.value||confirmation.value))
watch(modalOpen,value=>{if(typeof document==='undefined')return;document.documentElement.classList.toggle('workflow-modal-open',value);document.body.classList.toggle('workflow-modal-open',value)},{immediate:true})
onBeforeUnmount(()=>{if(typeof document==='undefined')return;document.documentElement.classList.remove('workflow-modal-open');document.body.classList.remove('workflow-modal-open')})
const blankStage=()=>({position:props.workflow.stages.length+1,name:'',status_key:'new',responsible_role:'',responsible_user_id:null,is_required:true,action_label:'',instructions:''})
const stageForm=useForm(blankStage()), runtimeForm=useForm({status:''})
watch(()=>[page.props.flash?.success,page.props.flash?.error],([success,error])=>{const message=error||success;if(!message)return;notice.value={type:error?'error':'success',message};setTimeout(()=>notice.value=null,3500)},{immediate:true})
const openStage=stage=>{editingStage.value=stage||null;stageForm.clearErrors();stageForm.defaults(stage?{position:stage.position,name:stage.name,status_key:stage.status_key,responsible_role:stage.responsible_role||'',responsible_user_id:stage.responsible_user_id,is_required:stage.is_required,action_label:stage.action_label||'',instructions:stage.instructions||''}:blankStage());stageForm.reset();stageModal.value=true}
const closeStage=()=>{stageModal.value=false;editingStage.value=null}
const saveStage=()=>{const options={preserveScroll:true,onSuccess:closeStage,onError:()=>notice.value={type:'error',message:'Tahap gagal disimpan. Periksa data form.'}};editingStage.value?stageForm.put(resolveRoute('workflows.stages.update',{workflow:props.workflow.slug,stage:editingStage.value.id}),options):stageForm.post(resolveRoute('workflows.stages.store',{workflow:props.workflow.slug}),options)}
const moveStage=(index,direction)=>{const ids=props.workflow.stages.map(s=>s.id),target=index+direction;[ids[index],ids[target]]=[ids[target],ids[index]];router.patch(resolveRoute('workflows.stages.reorder',{workflow:props.workflow.slug}),{stage_ids:ids},{preserveScroll:true})}
const confirmStageDelete=stage=>confirmation.value={title:'Hapus tahap?',message:`Tahap “${stage.name}” akan dihapus dari definisi. Ticket dan Task tidak ikut terhapus.`,method:'delete',url:resolveRoute('workflows.stages.destroy',{workflow:props.workflow.slug,stage:stage.id})}
const confirmWorkflow=action=>confirmation.value=action==='toggle'?{title:props.workflow.is_active?'Nonaktifkan workflow?':'Aktifkan workflow?',message:'Instance dan seluruh data terkait tetap dipertahankan.',method:'patch',url:resolveRoute('workflows.toggle',{workflow:props.workflow.slug})}:{title:'Hapus workflow?',message:'Penghapusan hanya diizinkan jika workflow belum pernah digunakan.',method:'delete',url:resolveRoute('workflows.destroy',{workflow:props.workflow.slug})}
const runConfirmation=()=>{busy.value=true;const options={preserveScroll:true,onSuccess:()=>confirmation.value=null,onFinish:()=>busy.value=false};confirmation.value.method==='delete'?router.delete(confirmation.value.url,options):router.patch(confirmation.value.url,{},options)}
const openRuntime=item=>{runtimeItem.value=item;runtimeForm.reset();runtimeForm.clearErrors()}; const saveRuntime=async()=>{if(!runtimeItem.value||runtimeForm.processing)return;runtimeForm.clearErrors();runtimeForm.processing=true;try{const {data}=await axios.patch(runtimeItem.value.status_update_url,{status:runtimeForm.status},{headers:{Accept:'application/json'}});runtimeItem.value=null;notice.value={type:'success',message:data.message||'Status workflow berhasil diperbarui.'};router.reload({only:['workflow','instances'],preserveScroll:true,preserveState:true})}catch(error){const message=error.response?.data?.errors?.status?.[0]||error.response?.data?.message||'Status gagal diperbarui. Periksa transisi dan izin Anda.';runtimeForm.setError('status',message);notice.value={type:'error',message}}finally{runtimeForm.processing=false}}
const operator=v=>({equals:'sama dengan',not_equals:'tidak sama dengan',contains:'mengandung'}[v]||v), labelStatus=v=>String(v).replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase()), progress=count=>`${props.workflow.total_items_count?Math.round(count/props.workflow.total_items_count*100):0}%`, formatDate=(v,time=true)=>v?new Intl.DateTimeFormat('id-ID',time?{dateStyle:'medium',timeStyle:'short'}:{dateStyle:'medium'}).format(new Date(v)):'—', statusClass=v=>v==='done'?'bg-emerald-50 text-emerald-700':v==='cancelled'?'bg-rose-50 text-rose-700':'bg-cyan-50 text-cyan-700'
</script>

<style scoped>
.card{border:1px solid #e2e8f0;border-radius:1rem;background:white;padding:1.25rem;box-shadow:0 1px 2px rgb(15 23 42/.04)}.dark .card,.dark .metric,.dark .modal{border-color:#334155;background:#0f172a}.metric{border:1px solid #e2e8f0;border-radius:1rem;background:white;padding:1rem}.metric p,.label{font-size:.7rem;font-weight:700;text-transform:uppercase;letter-spacing:.08em;color:#94a3b8}.metric strong{display:block;margin-top:.35rem;font-size:1.4rem}.primary,.secondary{display:inline-flex;align-items:center;justify-content:center;gap:.4rem;border-radius:.75rem;padding:.65rem 1rem;font-size:.875rem;font-weight:650}.primary{background:#0891b2;color:white}.secondary{border:1px solid #cbd5e1;color:#475569}.table-head th{padding:.75rem 1.25rem;text-align:left;font-size:.7rem;text-transform:uppercase;letter-spacing:.06em;color:#64748b}.order{display:flex;height:2.2rem;width:2.2rem;align-items:center;justify-content:center;border-radius:999px;background:#0891b2;color:white;font-weight:700}.menu{display:flex;align-items:center;gap:.6rem;padding:.6rem .8rem;color:#475569;text-align:left}.menu:hover{background:#ecfeff;color:#0e7490}.menu .material-icons{font-size:1.1rem}.menu.danger{color:#e11d48}.backdrop{position:fixed;inset:0;z-index:2147483000;display:flex;align-items:center;justify-content:center;background:rgb(15 23 42/.58);padding:1rem}.modal{width:100%;max-width:30rem;border-radius:1rem;background:white;padding:1.5rem;box-shadow:0 24px 60px rgb(15 23 42/.3)}.modal-head{display:flex;align-items:flex-start;justify-content:space-between}.modal-head h3{font-size:1.25rem;font-weight:700}.eyebrow{font-size:.7rem;font-weight:800;text-transform:uppercase;letter-spacing:.12em;color:#0891b2}.close{font-size:1.6rem;color:#94a3b8}.field{display:flex;flex-direction:column;gap:.4rem;font-size:.8rem;font-weight:650;color:#475569}.input{width:100%;border:1px solid #cbd5e1;border-radius:.75rem;background:transparent;padding:.65rem .8rem;font-size:.875rem}.dark .input{border-color:#475569;color:#e2e8f0}.actions{margin-top:1.5rem;display:flex;justify-content:flex-end;gap:.75rem}.fade-enter-active,.fade-leave-active{transition:opacity .2s}.fade-enter-from,.fade-leave-to{opacity:0}
:global(html.workflow-modal-open),:global(body.workflow-modal-open){overflow:hidden!important;overscroll-behavior:none}</style>
